### ISSUE TITLE
Worker is not authorized

### ISSUE THREAD

**Issue by njdro** [p4u/stratum-proxy-ng#1]
I'm not sure how much "testing" i will do, but with your proxy I receive:

```
2014-08-15 09:05:27,912 INFO proxy3333 stratum_listener.submit # [128ms] Share from [workername] (None) REJECTED, diff 128: (-2, u'Worker is not authorized', None)
```

which results in 100% Rejected.

I've used 3 other proxies that do not fail auth.

Thank you.

**Comment by p4u** [comment]
Can you post the command line options you are using to execute the proxy?

**Comment by njdro** [comment]
python2.7 ./stproxy-ng.py -o freedom.wemineltc.com -p 3339 -sp 3333 -sh 0.0.0.0 -xp 10001 

(allowing clients to send user/pass -- if i have to use a custom user/pass, i'd be okay with that.)

**Comment by p4u** [comment]
Yes, you have to define your custom user/password. It would be useful to add the feature to let the workers sent their own authentication.

-cu USER -cp PASSWORD
